### ISSUE TITLE
Mobiles

### ISSUE THREAD

**Issue by ghost** [g3n/g3nd#12]
Is mobile envisaged ?

If it run access the opengl engine we are good. In terms of integration with the GUI I am thinking of using flutter. It has an asynchronous resource loading pipeline and can accept opengl outputs.

Flutter and golang run on all desktops and mobiles with zero code changes today. you just need a simple binding wrapper written in dart to access golang.
You just do the normal gomobile bind for mobile

**Comment by leonsal** [comment]
Maybe in the future. We are currently documenting the existing code base because we got a low score from goreportcards:
https://goreportcard.com/report/github.com/g3n/engine

**Comment by gedw99** [comment]
ok

**Comment by gedw99** [comment]
You got an A+ now :)

Great work !

I think I can get this going on mobiles.

I just need a window to load it inside of which is not hard for Android and iOS.
That means it will also run on Chromebooks.

Then only bit would be translating touch gestures.
I think you can embed this inside flutter and let it handle all the complex touch gestures. 
This would mean matching up certain gestures to certain action in the golang code. At the moment all actions are a yes or no. You don't have any analog actions where the action has a percentage , like on a joypad ?

Anyway I think it's quite easy to get this working inside flutter. I suggest this because flutter has so much long term potential and is only getting better.

I can make a mini demo of a simple golang opengl test harness rendering inside it. That would be a good first step.

**Comment by danaugrs** [comment]
We definitely want to try to support mobile, and gomobile + Flutter seems like a great way to do it! I'll dig into it - let us know if you get something working!

And great point, we will have to add support for touch/analog inputs. I know Kivy (in Python) does cross-device input management particularly well - maybe we can take a look there for inspiration.

**Comment by gedw99** [comment]
Deal.

The Google team are progressing fast on flutter for desktop :)
They are using glfw but also talking about an SDL wrapper. So things are in flux.
Everything runs on Linux and Mac. Windows is getting close. Only hold up is the Microsoft UWP stuff - just a little bit of extra stuff to make it a first class citizen on Windows.

So the only challenge is how to get the 3d window and the flutter forms together. I played with dsl to load a few opengl will does in a docking fashion too.

So as I try things out I will put up test harnesses on GitHub to show progress.
I am definitely in over my head a bit but let's see

**Comment by gedw99** [comment]
I meant SDL, not DSL :)

**Comment by danaugrs** [comment]
Awesome to hear! Pretty cool that [they are using glfw](https://github.com/google/flutter-desktop-embedding/blob/688213e0e6cb6a5d6cf54b194f06ce3674fd73f0/linux/library/include/flutter_desktop_embedding/flutter_embedder.h#L20), it will be simpler to integrate with g3n.
Hopefully they add support for Windows soon. It would also be nice if it became an official Flutter project.

Keep me posted! 😄

**Comment by danaugrs** [comment]
Mobile support is being discussed here: https://github.com/g3n/engine/issues/114
