### ISSUE TITLE
[material->blending], zooming out makes everything go gray

### ISSUE THREAD

**Issue by xyproto** [g3n/g3nd#6]
When zooming out in the material->blending screen, everything suddenly goes gray. Not sure if it's a bug or not.

Cheers!

**Comment by leonsal** [comment]
It is normal. When zooming out the camera is getting farther from the scene.
It reaches a point where the scene is out of the camera frustum and it is not rendered any more
showing only the background color. In this demo this occurs with very little zoom because
the camera is already very far from the scene.
